### ISSUE TITLE
AttributeError: module 're' has no attribute 'strings'

### ISSUE THREAD

**Issue by Sembiance** [dhondta/python-tinyscript#26]
Attempting to use `ts.bruteforce_re(regex)` with `Python 3.10.10` results in error:
```
  File "/home/sembiance/tmp/env/lib/python3.10/site-packages/tinyscript/helpers/attack.py", line 150, in bruteforce_re
    for c in re.strings(regex):
AttributeError: module 're' has no attribute 'strings'
```

Is 're' a different module? Or should I be using an older version of Python?

**Comment by dhondta** [comment]
Hi @Sembiance 
Thank you for reporting.
`re` is part of the modules I refine in the `preimports` subpackage, adding some functionalities like the `strings` function. The helper you used from the `helpers.attack` subpackage was still relying on the original `re` while it wasn't loading the lazy refined module. I fixed this with the latest commit.

**Comment by dhondta** [comment]
@Sembiance Update deployed, you can upgrade with `pip install --upgrade tinyscript`.
