### ISSUE TITLE
Password length is always 10

### ISSUE THREAD

**Issue by IXEguy** [dhondta/python-tinyscript#28]
I'm using the following regex: `^[0-9QWERTYUqwertyu@]{11,15}` and it seems to work per regexr.

However, in the [pdf password script](https://gist.github.com/dhondta/efe84a92e4dfae3b6c14932c73ab2577), whenever I run a `len(p)` inside the for loop for pypdf, it always returns 10. I've bumped up the starting length from 11 to 12 and it still returns 10.

I even added a counter and let it run over the weekend & so far it is at `[INFO] Length: 10 | Passwords attempted: 16401000`

Am doing something wrong?

**Comment by dhondta** [comment]
Hi @IXEguy 
You can set this through the `max_repeat` parameter, which is set to `10` by default. See the documentation of the function : 
```sh
>>> help(re.strings)
Help on function strings in module tinyscript.preimports.regex:

strings(regex, max_repeat=10, any_set=None)
    Generate all possible strings from a regex pattern.
```

**Comment by dhondta** [comment]
Note that this parameter is mostly important for limiting the string generation from the regular expression when a wildcard is used. A possibility could be to adapt the logic so that your upper bound `15` automatically updates the `max_repeat` parameter. I will look into this and let you know.
